### ISSUE TITLE
Error: module 'pkcs11' has no attribute 'lib'

### ISSUE THREAD

**Issue by figbux** [danni/python-pkcs11#68]
Hello,

I'm getting this error with test codes after upgrading my python from 3.5.2 to 3.8.0. Is there any workaround; or should I downgrade (BTW to what version, exactly)?

Thanks!

**Comment by figbux** [comment]
OK, it seems I'm having some folder permission issues; running with `sudo` solves as a workaround. Not related with python version.
